### ISSUE TITLE
A issue about Unreal Engine 5.4 compatibility

### ISSUE THREAD

**Issue by AzuraZJ** [P1ayer-1/Libtorch-UE5#8]
**Describe the bug**
I tried porting the plugin to UE5.4 and fixed the compilation errors there. Before successfully compiling and submitting for push, I conducted some tests according to the quick start video on YouTube, but found that in UE5.4 the blueprint could not call all Tensor Constructors under UAtumLibraryTensors. I tried rebuilding the project several times, but to no avail.

**To Reproduce**
Steps to reproduce the behaviour:
1. After replace all UE_nodiscard with [[nodiscard]], It will compiles in UE5.4
2. I can create various assets and it works fine until using "Make Tensor XXX", where the blueprint cannot find UFUNCTIONs defined in UAtumLibraryTensors.

**Expected behaviour**
As you can see in the picture below, I can't find constructors, but other functions can be found

**Screenshots**
<img width="1647" alt="屏幕截图(67)" src="https://github.com/P1ayer-1/Libtorch-UE5/assets/142844595/faca76ba-f7cf-467a-a938-b22ab24ba67a">

**Environment Information**
- **OS:** Win10
- **Unreal Engine Version:** 5.4
- **Plugin Version:** v0.1.0
- **Built from:** Release

**Additional context**

**Comment by P1ayer-1** [comment]
Thank you for reporting the issue. I am investigating it now and will update you when I have more information.

**Comment by P1ayer-1** [comment]
Hi, I have uncovered the source of your issue.

It is because you replaced all instances of "UE_NODISCARD" with "[[nodiscord]]". 

Unreal expects that you use "UE_NODISCARD_CTOR" for constructors where callers are warned that they shouldn't ignore the return value. [[nodiscord]] is needed for non-constructors.

"UE_NODISCARD_CTOR" should be used for constructors such as "Make Empty Tensor". Below is an example how it should look for "Make Empty Tensor".

```
	/**
	 * Creates a new empty tensor
	 * 
	 * @param Class Type of tensor implementation
	 * @param Sizes Array of sizes
	 * @return The created tensor
	 */
	UE_NODISCARD_CTOR
	UFUNCTION(BlueprintCallable, Category = "ATUM|Tensor|Constructor", DisplayName = "Make Empty Tensor", meta = (
		AutoCreateRefTerm = "Sizes",
		DeterminesOutputType = "Class",
		CompactNodeTitle = "Empty Tensor",
		Keywords = "ATUM Constructor Make Empty Tensor Class Sizes"
	))
	static UObject* Empty(
		UPARAM(meta = (MustImplement = "/Script/Atum.AtumTensor")) const UClass* Class,
		const TArray<int64>& Sizes
	);
```

I will need to go through the code base to determine the correct macros to use in 5.4. I will not be able to implement the fix for the time being though. Which is why I have shared information on how to fix it for yourself. 


The deprecation of "UE_NODISCARD" and expected use of "UE_NODISCARD_CTOR" / "[[nodiscord]]" is mentioned in the comments of `Platform.h` for Unreal 5.4.

**Platform.h** - https://github.com/EpicGames/UnrealEngine/blob/5.4/Engine/Source/Runtime/Core/Public/HAL/Platform.h
